### ISSUE TITLE
Fails to read the first section if the file has a BOM

### ISSUE THREAD

**Issue by peterhoeg** [pixelb/crudini#103]
`crudini` fails to read the first section if the file has a BOM. Before we get into the BOM vs no BOM discussion, I would like to point out that the file was generated by a program that expects a BOM.

Here is the test file:

`$ cat test.ini`

```ini
[foo]
bar = baz

[woot]
hello = world
```

When the file has a BOM, we are not able to read the first section - the 2nd is fine:

```
$ file *
test.ini: Unicode text, UTF-8 (with BOM) text

$ crudini --get test.ini foo 
Section not found: foo

$ crudini --get test.ini woot
hello
```

But if we strip the BOM, we can:

```
$ sed -i $'1s/^\uFEFF//' test.ini 

$ file *
test.ini: ASCII text

$ crudini --get test.ini foo
bar

$ crudini --get test.ini woot
hello
```

This might be an `iniparse` issue of course (without having looked at the code).

**Comment by pixelb** [comment]
Right. We should support this, and also maintain the BOM if updating such a file
