### ISSUE TITLE
Problems with indents in ini files

### ISSUE THREAD

**Issue by fawzibr** [pixelb/crudini#104]
I'm dealing with an INI with indented keys, for example:

```
[section 1]
 key1=value1
```

If I try to add a new key with _crudini --set test1.ini key2 value2_ i get the following:
```
Source contains parsing errors: '<???>'
        [line  3]:  key1=value1
```

Also if the section is indented I get other problems, for example:

```
[section 1]
key1=value1

 [section 2]
key1=value1
key2 = value2
```

If I add a key to [section one] with `crudini --set test2.ini "section 1" "key2" "value2"` I end up with the following:
```
[section 1]
key1=value1

 [section 2]
key1=value1
key2 = value2
```
I guess it ignores [section 2] and adds it to the end. Also _crudini --get test2.ini_ only lists [section 1]. I think it should get sections/keys even if indented. Don't know if it's a crudini problem or iniparse problem though.

**Comment by pixelb** [comment]
Can you try with the `--ini-options=ignoreindent` option

**Comment by fawzibr** [comment]
It just gives me the help screen so i guess it's an error, the help screen only mentions the 'nospace' option. Btw I'm testing on latest ubuntu but will use on docker (alpine).

**Comment by pixelb** [comment]
You could try downloading the latest from github and using the script directly.

**Comment by fawzibr** [comment]
> You could try downloading the latest from github and using the script directly.

Downloading latest and using --ini-options=ignoreindent works. Thanks
