### ISSUE TITLE
crudini cannot parse /etc/krb5.conf because of indents

### ISSUE THREAD

**Issue by sebma** [pixelb/crudini#105]
Hi, I'm using `crudini` v0.9.4 from Ubuntu 24.04 and it seems it cannot parse `/etc/krb5.conf` :
```shell
$ crudini --get /etc/krb5.conf libdefaults
Source contains parsing errors: '<???>'
        [line  2]:      default_realm = myDOMAIN.LAN

$ echo $?
1
$
```

**Comment by sebma** [comment]
It seems it was because of indents, adding this `--ini-options=ignoreindent` option solved my problem.

**Comment by pixelb** [comment]
Also tangentially related: #45
