### ISSUE TITLE
When removing last section, file keeps growing

### ISSUE THREAD

**Issue by fawzibr** [pixelb/crudini#106]
If I have the following ini file:

```
-----
[section 1]
key=value

[section 2]
key=value
-----
```

If I remove the last section I get the following:

```
-----
[section 1]
key=value

-----
```

Notice there is a empty line at the end of the ini.  If I add a new section crudini will add an empty line and the section. So now the file looks like this:

```
-----
[section 1]
key=value


[section 2]
key=value
-----
```

If I keep deleting and then adding sections at the end of the file, the number of empty lines will keep growing. Maybe the file should be trimmed when rewriting it, or if the last line is empty just append the section.

**Comment by pixelb** [comment]
This is related to issue #94, but the solution for that didn't handle the case where _removing_ the section left a blank line. You could also have ever increasing blank lines in the middle of a file by --del and --set of alternating names, so this will be tricky to handle. What we want is to remove a blank line on top of a "[section]", which is tricky as iniparse doesn't give an option to do that. I suppose you could contrive some ini files where you didn't want to remove a blank line before a "[section header]", but that would be very unlikely. I can't see how to achieve this though, so I'll need to think about it

**Comment by pixelb** [comment]
Note this is a bit related to comments also. Consider...

```
# section comment
[section to delete]
blah = blah
```

In that case `--del 'section to delete'` would not remove the comment.

**Comment by fawzibr** [comment]
Right now, to solve the problem I'm doing 'cat -s myfile.ini | sponge myfile.ini', (-s, --squeeze-blank: suppress repeated empty output lines). Maybe something like that could be done.

**Comment by pixelb** [comment]
I suppose we could have `--ini-options=tidy` do that after all operations. It would be nice to do this automatically though. I suppose the "tidy" option would be useful in isolation anyway, so I'll probably add that anyway
