### ISSUE TITLE
Support nested sections

### ISSUE THREAD

**Issue by thoastbrot** [pixelb/crudini#27]
It would be nice if crudini supported nested sections, as for example in:

    [system]
      inventory = 0x8492384
      [[software]]
         update = yes
         upgrade = no
      [[config]]
         foo = bar

**Comment by pixelb** [comment]
Is there existing precedent for that format? The ini parser used by crudini doesn't support it anyway.
You might achieve much the same scheme by just naming sections appropriately? Like:
'''
[system]
  inventory = 0x8492384
[system/software]
  update = yes
  upgrade = no
[system/config]
  foo = bar
'''

**Comment by thoastbrot** [comment]
I just read on WP that INI doesn't support nested sections. It's something I know from pythons configobject. Sadly, I have no impact on the config file syntax.. but thanks for the hint.

**Comment by pixelb** [comment]
Ah right, that's specific to the third party configobj:
http://configobj.readthedocs.org/en/latest/configobj.html#the-config-file-format
BTW I adjusted the above example to avoid leading whitespace
as that's not supported, as used for multiline entries
