### ISSUE TITLE
crudini can leave locks files in HA configurations

### ISSUE THREAD

**Issue by aplanas** [pixelb/crudini#31]
Actually `crudini` can potentially leave .lck files when is in HA configurations. If STONITH decides to shutdown a node when is running a `crudini --get`, a `.lck` file will remain in the file system.

I propose to extend `--get` with an unsafe parameter `--no-lock` to avoid the creation of the lock file. This non default parameter can behave properly with the default mode of `--set` (that is `file_replace`), but will cause problems with the non default `--inplace` option.

**Comment by pixelb** [comment]
I'm a bit confused. There are no separate `.lck` files since commit 10875e6a

**Comment by aplanas** [comment]
Oh yes, I see!  As I see the current lock is over the file descriptor of the opened file. Am I right if I guess that this lock is only in memory and a reset of the node will free the lock, as a normal close?

**Comment by pixelb** [comment]
Right. I.E. if you upgrade to the latest version you should be fine
