### ISSUE TITLE
Whitespace around =

### ISSUE THREAD

**Issue by xsc27** [pixelb/crudini#33]
I want to be able to set a value like this:
`VAR=value`

rather than,
`VAR = value`

and if it is updating an existing value to preserve the absence of whitespace.

**Comment by pixelb** [comment]
I agree this would be a useful feature, and noted that at:
https://github.com/pixelb/crudini/blob/0f9a4c8/TODO#L39-L42

I would require updating or migrating away from the python-iniparse project

**Comment by karlicoss** [comment]
Agree, quite annoying when some programs are not picking up keyvalue pairs with spaces. I think `python-iniparse` is outdated anyway and only supports python2. Might be a good idea to use a bundled in  https://docs.python.org/3/library/configparser.html

**Comment by tzahari** [comment]
Also an issue for shell scripts / shell configs...

**Comment by Roemer** [comment]
I am having the very same issues while creating a ut99 docker image. The ini does not allow spaces around the equal sign.

In my case, I solved it by just replacing all lines with sed with the following:
```
sed -i -r "s/(.*?)\s*=\s*(.*)/\1=\2/g" UnrealTournament.ini
```

**Comment by ichtm** [comment]
Just built a tiny write-only wrapper script at:
https://github.com/ichtm/set_conf 

It uses configparser lib to accomplish this non-spaced-eqal-sign task. It contains a shell header line,  so you can run it from bash like 

    ./set_conf.py myfilename.conf mysection myoption 42

It's explicitly built for write-only tasks like deployment with Ansible / Docker / K8S environments and so on. It auto-creates non-existing sections and options. Maybe this is useful for someone.

**Comment by perkinslr** [comment]
This is easy enough to fix via reflection.  The issue is the default separator set in `iniparse.ini.OptionLine.__init__`, so we just replace the original `__init__` with a wrapper that changes the default.

    from iniparse import ini
    orig_ol_init = ini.OptionLine.__init__
    ini.OptionLine.__init__ = lambda self, name, value, separator="=", *args, **kw: orig_ol_init(self, name, value, separator, *args, **kw)

**Comment by burner1024** [comment]
Please add non-whitespace option at last. This is clearly a common issue.

**Comment by giondo** [comment]
+1 non-whitespace option

**Comment by cclecle** [comment]
> I am having the very same issues while creating a ut99 docker image. The ini does not allow spaces around the equal sign.
> 
> In my case, I solved it by just replacing all lines with sed with the following:
> 
> ```
> sed -i -r "s/(\S*)\s*=\s*(.*)/\1=\2/g" UnrealTournament.ini
> ```
> 
> edit: sed does not support non-greedy regex, so I replaced the `(.*?)` with a `(\S*)`

man... # metoo
+1000
Meanwhile... Ok lets go for yet another sed hack :)

**Comment by Roemer** [comment]
Haha that's what I needed it for as well. Check out my UT image, I think it is quite complete and used by quite a few. Help improve that instead of creating another: https://github.com/Roemer/ut99-server

**Comment by vtwaldo21** [comment]
I'm not sure it is intentional or will be future proof, but it looks like it does preserve the lack of spaces when the key is already there. So it shouldn't be a hard fix. You can kind of trick it by just running the command twice to get the desired format. 

crudini --set file.ini key=value
crudini --set file.ini key value

Of course a flag would be way better than this hack

**Comment by mschmitt** [comment]
@vtwaldo21 thanks for that! I expect that explicitly deleting the value before re-adding it, will make your workaround more reliable:

```
# /usr/lib/systemd/system/avahi-daemon.service.d/local.conf
[Service]
ExecStartPre=crudini --del --existing=section /etc/avahi/avahi-daemon.conf 'publish' 'disable-publishing'
ExecStartPre=crudini --set --existing=section /etc/avahi/avahi-daemon.conf 'publish' 'disable-publishing=yes' 'dummy'
ExecStartPre=crudini --set --existing=section /etc/avahi/avahi-daemon.conf 'publish' 'disable-publishing' 'yes'
```

(Although at this point, just sed'ing away the blanks might be more intuitive.)

**Comment by pixelb** [comment]
There are a few caveats with the sed solutions provided here:
* doesn't handle ':'
* doesn't handle params with spaces in name
* doesn't handle multiline with leading spaces
* isn't atomic

**Comment by pixelb** [comment]
pr #89 adds support for a new `--ini-options=nospace` command line option, to enforce the use of name=val format throughout a file
