### ISSUE TITLE
Platform and Python support

### ISSUE THREAD

**Issue by thorstenkampe** [pixelb/crudini#35]
`Crudini` does not work with Python 3 or under Windows - although you can install it via `pip` without a problem. Will `Crudini` be improved to support Windows and Python 3? If not I would at least suggest to mention the limitations in the Readme.

**Comment by pixelb** [comment]
It should be relatively easy to get windows and python3 support.
I'll prioritize that...

**Comment by deinok** [comment]
@pixelb I can give help with the port to windows

**Comment by pixelb** [comment]
@deinok That would rock! It shouldn't be too hard, but I don't have a copy of windows handy. I've created a new branch where the top two commits should document the problem (issue #26)
https://github.com/pixelb/crudini/commits/nt

**Comment by deinok** [comment]
@pixelb okey, this weekend i will try it. Also, good job ;)

**Comment by thorstenkampe** [comment]
Microsoft offers virtual machines for developers: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ . You can use them for ninety days and then revert to an initial snapshot to avoid downloading again.

**Comment by pixelb** [comment]
Addressed by commit 0f2c0b03
