### ISSUE TITLE
Single-token values without '=' and RHS

### ISSUE THREAD

**Issue by crayfishuk** [pixelb/crudini#38]
The MySQL ini file has a number of settings which are either present or absent - but have no value (e.g. `[mysqld]` - `skip-external-locking`,  and `[mysqldump]` - `quick`, `quote-names` for just a few).  There doesn't seem to be support for thes: it comes up with a parse error.

In addition - it reports parse-errors on `!include ...` lines which seem to be widespread in ini files too...

**Comment by pixelb** [comment]
Yes supporting variables without an = is the first item in TODO and should be supported.
It would require updates to iniparse though

!include files are also not supported, and would be quite complicated to do so
