### ISSUE TITLE
Crudini omits keys/params

### ISSUE THREAD

**Issue by thorstenkampe** [pixelb/crudini#39]
Crudini omits certain keys in sections like `remote` (see below); tested on Linux and Cygwin. It looks like the underlying `iniparse` library is the culprit.

Can you confirm the issue and tell which kind of keys are dropped? If this is potentially occuring with a multitude of key names I would have to drop Crudini for my current project.

```
> cat transport.ini                                                                                                                            [Transport]
local  = /tmp
remote = /tmp/TEST.sh
upload = false
> crudini --get --format sh transport.ini Transport
local=/tmp
upload=false
```

**Comment by pixelb** [comment]
Whoa that's a crazy bug.
I confirmed it's in iniparse with:

```python
import iniparse
from cStringIO import StringIO
p=iniparse.ConfigParser()
p.readfp(StringIO("[1]\nremote=1\nemote=2"))
print p.items(p.sections()[0])
```

I don't see "remote" mentioned in the iniparse source,
so I'll need to dig a bit...

**Comment by pixelb** [comment]
Whoa, any line that starts with "rem" is treated as a comment. Ouch.

**Comment by thorstenkampe** [comment]
Thanks for the quick fix. Appreciated!
