### ISSUE TITLE
read complete ini file in shell format

### ISSUE THREAD

**Issue by thorstenkampe** [pixelb/crudini#41]
Does `crudini` have support for reading the whole content (sections, keys) in one read with `--format sh`? 

The documentation suggests I have to iterate over all sections in order to do that. That is inefficient and time consuming because the ini file is read (opened, closed) for each iteration...

**Comment by pixelb** [comment]
`--format=lines` was added to give general flexibility like that. With some caveats on the format of the values, something like this might suffice, to give unique section_param=value items:

    eval $(crudini --format=lines --get file.ini | sed 's/\[ \(.*\) \]/\1/; s/ = /=/; s/ /_/g')

This might be awkward/useful enough to warrant a --format=lines-sh option
