### ISSUE TITLE
symbolic link is changed to a regular file

### ISSUE THREAD

**Issue by apevec** [pixelb/crudini#43]
(copy-edited from a private bz, replacing openstack-config with crudini in examples)

    # ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
    # ll /etc/neutron/plugin.ini
    lrwxrwxrwx. 1 root root 37 Jun 13 14:38 /etc/neutron/plugin.ini -> /etc/neutron/plugins/ml2/ml2_conf.ini

  Then, configure the plugin file with the crudini command.

    # crudini --set /etc/neutron/plugin.ini ml2 tenant_network_types vlan
    # ll /etc/neutron/plugin.ini
    -rw-r-----. 1 root neutron 3959 Jun 13 14:39 /etc/neutron/plugin.ini

  The symbolic link file is changed to a regular file and its content is
  different from the original file.

    # diff -i -U0 /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
    --- /etc/neutron/plugins/ml2/ml2_conf.ini       2016-06-10 16:18:14.364982681 +0900
    +++ /etc/neutron/plugin.ini     2016-06-13 14:39:40.022264671 +0900
    @@ -14 +14 @@
    -tenant_network_types = vxlan
    +tenant_network_types = vlan

**Comment by pixelb** [comment]
Hey Alan! Sorry about that.

A workaround with released versions is to using the --inplace option,
though that is not an atomic replace.
