### ISSUE TITLE
add flag to allow creating a parameter if it does not exist

### ISSUE THREAD

**Issue by frippe75** [pixelb/crudini#46]
Not sure if I'm missing something but i would like to have crudini add the parameter if it's missing using a flag --allow-missing or something.

using openstack-config command which basically calls crudini by passing all given arguments.
Some boilerplate files sometimes miss a few default parameters which really should be there.

**So my script will fail with:**
Parameter not found: rabbit_hosts

**Comment by pixelb** [comment]
That should be supported by default (unless --existing is specified). I.E. This will create file/section/param:

    crudini --set new.ini section1 parameter1

What version of crudini are you using?

**Comment by frippe75** [comment]
Hmm you are right it does work calling crudini directly. Not sure why I didn't test it, simply jump to conclusion it had to be crudini

openstack-config simply does this:
exec crudini "$@"

I think you can close this bug and I'll hunt it down where it belongs. Thanks for the quick response

**Comment by pixelb** [comment]
I'm guessing you're using an older version of openstack-config that didn't call out to crudini.
