### ISSUE TITLE
Parsing conf files where same param can be defined multiple times

### ISSUE THREAD

**Issue by monstruooo** [pixelb/crudini#49]
Just wanted to draw your attention to ntp.conf

server 0.rhel.pool.ntp.org iburst
server 1.rhel.pool.ntp.org iburst
server 2.rhel.pool.ntp.org iburst
server 3.rhel.pool.ntp.org iburst

This is not an abstract example. I just tried to modify it using crudini, but I couldn't find a way to do it

**Comment by pixelb** [comment]
There basically no overlap in this file format with the "ini" format AFAICS
