### ISSUE TITLE
--set behaves more like --add

### ISSUE THREAD

**Issue by WelliSolutions** [pixelb/crudini#51]
Running the `--set` command twice for the same parameter in the same section results in 2 entries. Thus it behaves more like an "add" operation. It does not replace the existing value by the new one.

I have tried this with a MySQL configuration file on Debian 9. Details and commands: [see my question on AskUbuntu](https://askubuntu.com/a/995658/242307).

Workaround: use `--del` before using `--set`.

**Comment by pixelb** [comment]
The issue is you used port=3333 in the command. You need to separate the parameter and value like

    crudini --set /etc/mysql/my.cnf mysqld port 3333

cheers
