### ISSUE TITLE
Feature Request: Find section where parameter is defined

### ISSUE THREAD

**Issue by Nuru** [pixelb/crudini#55]
I have a use case where I would like to find the section in which a parameter is set to a specific value. Given the `config_file`:
```
[host1]
user=user1

[host2]
user=user2
```
I would like `crudini --find config_file user user2` to output `host2`. This would help me use the information I have to find the section I want to modify or identify to the user as being active.

**Comment by pixelb** [comment]
crudini tries to integrate with other utilities where possible.
Does this work for you?

    crudini --get --format=lines t.ini | grep 'user = user2'

**Comment by Nuru** [comment]
@pixelb I did not realize `--format=lines` would contain the information I was looking for. Still, not to sound ungrateful, but 
```
crudini --get --format=lines t.ini | grep 'user = user2'
```
does not quite get me what I need. I would have to do 
``` 
crudini --get --format=lines t.ini | grep 'user = user2' |  sed  's/^\[ \([^]]*\) ].*$/\1/'
```
which of course I can do, but it took me a while to figure that out, and if you could add it to `crudini` then it would be easier for the next person.

Obviously this is not a critical feature, but still one I would use if it were available.

**Comment by pixelb** [comment]
You could use this instead of your sed:
    cut -f2 -d' '

This is the unix philosophy of not adding functionality to something unless it's needed
cheers

**Comment by Nuru** [comment]
I cannot use `cut` because there is no promise that the section name does not have a space in it.

I believe the unix philosophy is for tools to do only 1 thing but to do that 1 thing very well. In particular, utilities are specialists in handling edge cases that other tools might miss. I think this request fits, and it is something I would use, but of course it is up to you.
