### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by tdmalone** [pixelb/crudini#58]
Hi there!

Just wondering if you had any plans to add Python 3 support?

I'm a bit of a newbie to Python so I tried turning the `print`, `except` and `raise` statements into functions which possibly got me most of the way there... until I came across issues with `cStringIO` and `ConfigParser` not being available.

Thanks for what you've done so far and thanks in advance if a Python 3 version is possible!

**Comment by pixelb** [comment]
python 3 support is coming real soon. cheers

**Comment by toabctl** [comment]
and please don't forget to do a new pypi release when py3 support is ready :)

**Comment by imalik-rms** [comment]
any update on this ? still getting
```
/# crudini
  File "/usr/local/bin/crudini", line 39
    print str(e)
            ^
SyntaxError: invalid syntax
```

**Comment by razorsedge** [comment]
Plus 1 for Python 3 support.

**Comment by pixelb** [comment]
I've not pushed this to pypi yet as it depends on python-iniparse which doesn't have a python3 version on pypi yet. Though crudini does support python3 now, and has been released to fedora as python3 only as python-iniparse has been adjusted to support python3 there

**Comment by toabctl** [comment]
@pixelb did you try to contact the iniparse owner on pypi to get a new upload there? I didn't found an email or something to contact him...

**Comment by pixelb** [comment]
I did not try to contact the owner.
I see it seems to have transferred from http://code.google.com/p/iniparse/ to https://github.com/candlepin/python-iniparse

@jirihnidek do you know the details here, or about the possibility of a pypi release?

**Comment by marcobrador** [comment]
Looks like iniparse 0.5 is now available in PyPI: https://pypi.org/project/iniparse/0.5/#history

Would it be possible to push crudini 0.9.3 as well? Thanks!

**Comment by jirihnidek** [comment]
Yeah, it is possible to install `iniparse` from PyPI. Python 2.x and Python 3.x is supported.

**Comment by aspiers** [comment]
Any progress on this?

**Comment by aspiers** [comment]
Just to confirm - installing via

    pip install -e git+https://github.com/pixelb/crudini.git\#egg=crudini

works nicely.  So it seems all that is needed now is to push a new release.

**Comment by Meetsch** [comment]
+1 to push a new release to pypi

**Comment by rangolisharan** [comment]
Hi, any update on this?

**Comment by pixelb** [comment]
crudini 0.9.3 is now on pypi

**Comment by Meetsch** [comment]
great, thank you!
