### ISSUE TITLE
works in bash, but not sh

### ISSUE THREAD

**Issue by emayssat** [pixelb/crudini#59]
crudini does NOT work in sh on my side

$ crudini --version
crudini 0.7

$ crudini --get /home/vagrant/.python-gitlab.cfg default url                                                                    
https://gitlab.eng.xxxxxxx.com/`
$ sh                                                                                                                           
$ crudini --get /home/vagrant/.python-gitlab.cfg default url
  File "/usr/local/bin/crudini", line 39
    print str(e)
            ^
SyntaxError: invalid syntax
$ exit

**Comment by pixelb** [comment]
This is probably due to the python interpreter being used.
You should be able to edit the first line of /usr/local/bin/crudini to explicitly reference python2
python2/3 support has just been merged upstream

**Comment by emayssat** [comment]
Indeed I had to prefix  crudini with python2 as follow:

/usr/bin/python2 /usr/local/bin/crudini
