### ISSUE TITLE
Loop thru .ini sections possible ?

### ISSUE THREAD

**Issue by palansher** [pixelb/crudini#69]
Hello !

Cannot imagine how to get list of sections in ini file. I just need to loop thru them using  bash.
I see it is not implemented. Any advice/ workaround will be much appreciated.

Thank you for nice tool!

Vladimir

**Comment by pixelb** [comment]
```
$ for section in $(crudini --get example.ini); do
  echo do something with $section
done
```

**Comment by palansher** [comment]
> ```
> $ for section in $(crudini --get example.ini); do
>   echo do something with $section
> done
> ```

OMG! it works! 
Thank you for quick answer your and live project! 
Not bad idea to include to examples...
