### ISSUE TITLE
New crudini versions for Ubuntu

### ISSUE THREAD

**Issue by palansher** [pixelb/crudini#70]
Good evening!

Ubuntu 18.04 offers old v0.7 crudini  package to install. 
Maybe you can advise what method to use to install latest crudini  verstion in Ubuntu ? Some pip or something  else?
I plan to use  crudini mostly in bash environment.

PS: just found #23 
maybe it still working: 
`apt-get install python-iniparse; curl https://raw.githubusercontent.com/pixelb/crudini/master/crudini > /usr/local/bin/crudini && chmod a+x /usr/local/bin/crudini
`

but it seems it at least doesn't copy man page

Thanks in advance!

**Comment by pixelb** [comment]
I see the latest is in debian stable now
