### ISSUE TITLE
Error when using 0.9 on Alpine

### ISSUE THREAD

**Issue by ravensorb** [pixelb/crudini#71]
I am working with Alpine and it seems that 0.9 is the current version avialable on that platform.  When I install it, I am getting the following error

```
File "/usr/bin/crudini", line 39
    print str(e)
             ^
 SyntaxError: invalid syntax
````

If it helps the version of python installed to 3.8.5

**Comment by pixelb** [comment]
Please update to crudini 0.9.3 (which is now on pypi).
That supports python 3
