### ISSUE TITLE
Release 0.9.3 missing on PyPi

### ISSUE THREAD

**Issue by frenck** [pixelb/crudini#72]
Hi there!

Quick question/request: Could you put up the latest release onto PyPi as well?

GitHub shows release 0.9.3, which adds Python3 support.

<https://github.com/pixelb/crudini/releases>

![image](https://user-images.githubusercontent.com/195327/98135462-26e49200-1ec0-11eb-9263-9741fdcfc382.png)

However, PyPi currently reports 0.9 as the latest version:

<https://pypi.org/project/crudini/#history>

![image](https://user-images.githubusercontent.com/195327/98135485-2f3ccd00-1ec0-11eb-9e7e-1e533bf01ba0.png)

Thanks in advance! 👍

**Comment by pixelb** [comment]
Done
