### ISSUE TITLE
Find duplicates using crudini?

### ISSUE THREAD

**Issue by palansher** [pixelb/crudini#78]
Good day!

Is there any way to find in an *.ini file, using crudini, the duplicates of:
- section name duplicates
- key duplicates inside section

I see now that crudini just gets 1st record from dupes. And after that, it is difficult to search any dupe errors sourced from an incorrect ini file.
Excuse me for such a strange question...
Any your advice (how to found /locate dupes in big ini file) will be highly appreciated!

**Comment by pixelb** [comment]
crudini doesn't support that currently, as the iniparse library it uses will take the value of the last instance of a key
