### ISSUE TITLE
Merging sections uses wrong values

### ISSUE THREAD

**Issue by erhhung** [pixelb/crudini#88]
Consider these two ini files:

"`old_ini`":
```ini
[section1]
foo = old1foo
bar = old1bar
baz = old1baz

[section2]
foo = old2foo
bar = old2bar
baz = old2baz
```
"`new_ini`":
```ini
[section2]
foo = new2foo
bar = new2bar
baz = new2baz

[section3]
foo = new3foo
bar = new3bar
baz = new3baz
qux = new3qux
```

And running the following `--merge` operation to update `section2` values from new to old:
```ini
$ crudini --merge --output=- old_ini section2 < new_ini

[section1]
foo = old1foo
bar = old1bar
baz = old1baz

[section2]
foo = new3foo
bar = new3bar
baz = new3baz
qux = new3qux
```

Why are values from **section3**—or, rather, the **very last** set of values from the second file—being used to update values in the specified section: **section2**?

### Expected Behavior

The merge operation should use values only from the specified section, resulting in:
```ini
[section1]
foo = old1foo
bar = old1bar
baz = old1baz

[section2]
foo = new2foo
bar = new2bar
baz = new2baz
```

_Version: **crudini 0.9.3**_

**Comment by pixelb** [comment]
I agree this is confusing, but also most flexible.
To do what you want (i.e. only consider a single section for merging) you can:
```
crudini --get --format=ini new_ini section2 | crudini --merge --output=- old_ini section2
```

As originally written (and as documented in crudini tests,
when you specify a section to merge, then crudini will merge params from all sections to the specified one
