### ISSUE TITLE
How to use crudini natively in the textconv line for git diff

### ISSUE THREAD

**Issue by KlfJoat** [pixelb/crudini#90]
I have a number of ini files under git version control. The various tools that use and update the files use whatever method they like for updates, and sometimes rearrange sections or vars in a section however they see fit.

I've been using crudini to compare them with the excellent `--format=lines` then `| sort` mechanism you pointed out in the docs.

I have created an entry in `.gitattributes` and `[diff "ini"]` section in my git config (humorously, itself an ini file). This way it will show me the section heading in the "function name" part of a hunk header.  And it uses a script for the `textconv` setting that wraps crudini so that `git diff` shows me the pretty crudini diff.

But I'm wondering... is there a way to use crudini in my `textconv` line without the wrapper script?

I know it seems like a minor thing, but the `.gitconfig` and `.gitattributes` are already under version control. I'd rather not add another file.

The requirement by git of the `textconv` program is:
> [The textconv config option is used to define a program for performing such a conversion. The program should take a single argument, the name of a file to convert, and produce the resulting text on stdout.](https://git-scm.com/docs/gitattributes#_performing_text_diffs_of_binary_files)

I've tried all I can figure with redirection and piping, but can't figure out how to meet the requirement that the last thing on the line is the file to be read by crudini.

**Comment by pixelb** [comment]
That usage with git diff is cool!

For simple wrappers one generally can use `sh -c '...'`.
Now sh -c has a few gotchas with quoting and argv processing.
The documented form is:
```
sh -c command_string [command_name [argument...]]
```
Note that the command_name is explicit here, so should generally be specified when processing arguments.

BTW a general way to debug what args are passed where is
```
strace -s1000 -o exec.strace -e verbose=execve,execveat -e trace=execve,execveat -f <your command>
```
So replace <your command> above with `git diff`

Given that git just hardcodes the last param as the filename, then you want the following textconv:

```
[diff "ini"]
        textconv = sh -c 'crudini --get --format=lines "$1" | sort' crudini
```

**Comment by KlfJoat** [comment]
Yeah, I love using textconv to put a human-readable diffs up of complicated files (ODF with `odt2txt` or `unoconv`) or metadata (`exif` does metadata for basically everything else).  I've got quite the long global `.gitattributes`.

Your solution works for me.  Thanks!  I always forget `sh -c` when I'm trying to work through solutions. I don't know why.  I added `--` before the `$1`... just to ensure that nothing gets mistaken as an argument to crudini.

I do have a question, though. What use does `crudini-sorted-lines` have? It doesn't work without it, but I can't figure out why. When left out, the `crudini` help is shown without an error message.

To document my final configuration here, so that others searching can find it...

### Human-readable `git diff`s of ini files
To your [`gitattributes` file](https://git-scm.com/docs/gitattributes), at the appropriate level add the following line. You can change the `*.ini` part or add other lines for other extensions or globs you want to use `crudini` with.
```ini
*.ini diff=ini
```

To your [`gitconfig` file](https://git-scm.com/docs/git-config), at the appropriate level add the following section. You should not change any part of this.
```ini
[diff "ini"]
    textconv = sh -c 'crudini --get --format=lines -- "$1" | sort' crudini-sorted-lines
```

### Appropriate level
When I say "at the appropriate level", that's because `git` checks for config files in an order of precedence. Also your use case may vary. For my professional use case, I put the `.gitconfig` and `.gitattributes` files with the configurations above into the root of the repository because I wanted it to apply to every file in only this repo.  AND I added them to the repo so that the other people using the repo need the feature.  

But for my personal system, I added these configs to my user-wide ("global" in `git` parlance) `.gitconfig` and `.gitattributes` files in `$HOME`.

### Bonus
If you don't want to use `crudini` to `git diff` your ini files, say because there isn't as much churn as with mine, there's still a little `git diff` hack that I picked up from [a blog post](https://jnrowe.github.io/articles/tips/Context_aware_diffs_with_git.html). A normal `git diff` will show a "hunk header", which is some context about the function that the diff is in. This shows you the ini file section header your diff is in. **This is not compatible with the `crudini` usage above.**
```ini
[diff "ini"]
    xfuncname = "^\\[\\(.*\\)\\]$"
```

### References
* https://git-scm.com/docs/gitattributes#_performing_text_diffs_of_binary_files

**Comment by pixelb** [comment]
`crudini-sorted-lines` is just a descriptive placeholder, that `sh -c ...` will put into argv[0], i.e. $0

Otherwise the file name becomes $0, as is the case in the more succinct but hackish second form in my comment.

Good. point on the `--` as defensive programming to avoid file names ever being treated as options by crudini. I've amended my comment appropriately
