### ISSUE TITLE
Split lists on any whitespace

### ISSUE THREAD

**Issue by ekohl** [pixelb/crudini#91]
crudini exposes `--list-sep` as an option, but it defaults to `,`. In our application it is a whitespace separated list (technically newline separate). However, it's impossible to get crudini to use expose `str.split(None)` behavior. Am I missing something?

**Comment by pixelb** [comment]
You can currently explicitly select newline at a unix shell using:
```
crudini --list --list-sep=$'\n' --set file.ini section listname1 newitem
```
That will update an ini file like:
```
[section]
listname1 = item
 newitem
listname2 = blah
```
Now we could I suppose support any whitespace with `--list-sep=`,
then the updated list would use the first whitespace delimiter used in the list.

**Comment by ekohl** [comment]
> You can currently explicitly select newline at a unix shell using:
> 
> ```
> crudini --list --list-sep=$'\n' --set file.ini section listname1 newitem
> ```

That does indeed work. I learned something new. With that my immediate need is resolved, but I like your idea of the empty string to match any whitespace. That's actually something I instinctively tried while looking and `string.split('')` is invalid anyway. :+1:
