### ISSUE TITLE
get gives pipes deprecated warning on newer versions of Python

### ISSUE THREAD

**Issue by JamieJen** [pixelb/crudini#95]
It gives the following output before the value that is retrieved with get:-
`crudini: Deprecation Warning: 'pipes' is deprecated and slated for removal in Python 3.13`

I fixed like this:-
`--- a/crudini 2023-05-31 16:16:55.754846477 +0100 `
`+++ b/crudini 2019-08-30 12:29:59.000000000 +0100 `
`@@ -17,7 +17,7 @@ `
`import hashlib `
`import iniparse `
`import os `
`-import pipes `
`+import shlex `
`import shutil `
`import string `
`import tempfile `
`@@ -295,7 +295,7 @@ `
`             sys.exit(1) `
`         if value == 'crudini_no_arg': `
`             value = '' `
`-        sys.stdout.write("%s=%s\n" % (name, pipes.quote(value))) `
`+        sys.stdout.write("%s=%s\n" % (name, shlex.quote(value))) `
` `  
` `  
`class Crudini(): `
`@@ -938,7 +938,7 @@ `
` `
`                 if self.verbose: `
`                     def quote_val(val): `
`-                        return pipes.quote(val).replace('\n', '\\n') `
`+                        return shlex.quote(val).replace('\n', '\\n') `
`                     what = ' '.join(map(quote_val, `
`                                         list(filter(bool, `
`                                                     [self.mode, self.cfgfile,`

**Comment by pixelb** [comment]
Already handled in commit e1650941
Please upgrade (to 0.9.4)

**Comment by JamieJen** [comment]
Ah, thanks, turns the version with Buildroot that we are using is old at 0.9.3
